### ISSUE TITLE
Subfeatures for later additions

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#1160]
Most features are launched with an initial API shape and then evolve in many steps over time. Fetch is an example of this, where `fetch()` became Baseline in 2017, and the `Request` `destination` property followed in 2018. So far we've just excluded such later additions from our source YAML files, and left a lot of TODOs.

So far we've had two ideas for how to handle this:

- Just add new features with their own identifier, name, description, etc.
- Allow features to be a more living concept, and make it clear what the status of every part is via https://github.com/web-platform-dx/web-features/issues/979, giving the BCD keys individual Baseline statuses.

Because most features evolve in many steps, the overhead of handling minor additions is a major consideration. This is the main drawback of the first option above, that we'd need to name and describe lots of such features.

Brainstorming with @atopal @nairnandu @petele @rachelandrew we have a third option, which is a kind of "light" features. By example:

```yml
subfeatures:
  picture-in-picture-window:
    name: enterpictureinpicture event pictureInPictureWindow property
    compat_features:
      - api.PictureInPictureEvent
      - api.PictureInPictureEvent.PictureInPictureEvent
      - api.PictureInPictureEvent.pictureInPictureWindow
  picture-in-picture-pseudo:
    name: ":picture-in-picture pseudo-class"
    compat_features:
      - css.selectors.picture-in-picture
```

This requires an identifier and a name per subfeature, but nothing else.

@ddbeck WDYT?

**Comment by captainbrosset** [comment]
> This requires an identifier and a name per subfeature, but nothing else.

I think there will be cases where we'll also need to describe those sub-features. Whether we do this by adding a description field, or just by making the name longer, I sense that it will be similar work than option 1 above.

I'm not saying I'm against this solution though. It does seem like in many cases, it will be less work.

**Comment by captainbrosset** [comment]
This came up in our bi-weekly Baseline call today: [notes](https://docs.google.com/document/d/1ree75ImLZjf60lTZ3BhCaLHygxgywr7SBXp-q0xPs8A/edit#heading=h.6gou55b9mud1).

**Comment by ddbeck** [comment]
There are some things that I like and dislike about this idea, but I want to tease apart some goals of this first. What I'm hearing here (and from the discussion on the Baseline call earlier today) is threefold:

- **There ought to be an easy way to get status information for some slice of a broader feature.** Sometimes you want to show a whole feature's status, description, etc. (e.g., a webstatus.dev entry, a caniuse entry, or an API overview page on MDN for Picture-in-Picture), while sometimes you want to show the status of some slice of that feature (e.g., a web.dev article about Picture-in-Picture events or an MDN reference page for `requestPictureInPicture()` _of_ Picture-in-Picture). Both should practical and straightforward.

- **There ought to be an easy way to author (or otherwise cut) a slice of a feature.** I shouldn't have to make a whole new file, from scratch, to get at these slices. The absurdist rejection of this idea would be to create 10,000 single-compat-key web-features features so that MDN can show accurate statuses for every reference page.

- **There ought to be no fixed size to slices of features.** That is, there should be some resolution to feature descriptions in between the whole API from inception and a single BCD key and points in between.

I think these are all reasonable aims. I'm not sure we have to fix them all in one change, however.

Things I like about this proposal:

- It gives structure to later additions.
- It puts that structure alongside the existing feature information.

Things I don't like about this proposal:

- It's only marginally easier than creating individual feature files for each slice. I still have to give an identifier and name to each cluster of compat keys. I have to decide whether those clusters are meaningful to developers' long-term.
- It makes the lumping and splitting exercise smaller, but it doesn't actually dispense with it. I now get to move a bunch of "should this be its own feature?" questions into "should this be its own slice?" questions. It's probably easier to decide to slice than it is to mint a new feature, but I still have to draw the line.

Now for the "yes, and…" bit: one thing that might tip me to pro from anti would be _anonymous_ slices. That is, something like this instead:

```yaml
name: Picture-in-picture (video)
description: The picture-in-picture API allow websites to create…
compat_features:
  - - api.Document.exitPictureInPicture
    - api.Document.pictureInPictureElement
    - api.Document.pictureInPictureEnabled
    - api.HTMLVideoElement.disablePictureInPicture
    - api.HTMLVideoElement.enterpictureinpicture_event
    - api.HTMLVideoElement.leavepictureinpicture_event
    - api.HTMLVideoElement.requestPictureInPicture
    - api.PictureInPictureWindow
    - api.PictureInPictureWindow.height
    - api.PictureInPictureWindow.resize_event
    - api.PictureInPictureWindow.width
    - api.ShadowRoot.pictureInPictureElement
  - - api.PictureInPictureEvent
    - api.PictureInPictureEvent.PictureInPictureEvent
    - api.PictureInPictureEvent.pictureInPictureWindow
  - css.selectors.picture-in-picture
  - http.headers.Permissions-Policy.picture-in-picture
```

(I suspect, in practice, most slices would end up being—in the absence of functional subfeatures—"1st generation of interoperable items", "2nd generation of interopable items", and so on.)

Perhaps we could do something on the dist side to make addressing slices in a stable way (e.g., annotating each slice with a permanent key), or just expect consumers to query slices by key (e.g., get me the slice containing…). We'd then leave it to consumers to make contextual decisions about how to name these things (e.g., you write your own description and say, "Events of `<insert official feature name>`").

(This also implies we'd still allow https://github.com/web-platform-dx/web-features/issues/979.)
