### ISSUE TITLE
compute_from suppresses deprecation warnings

### ISSUE THREAD

**Issue by jamesnw** [web-platform-dx/web-features#1894]
Minimal nonsense reproduction, `api.SVGAnimateColorElement` is deprecated, `html.elements.del` is not.

```yml
name: deprecated
description: deprecated
compat_features:
  - api.SVGAnimateColorElement
  - html.elements.del
```

`npm run dist -- path/to/file` prints the warning:

```
warn: [feature id]: contains at least one deprecated compat feature and can never be Baseline. Was this intentional?
```

Adding a status.compute_from suppresses the deprecation warning. 

```yml
name: deprecated
description: deprecated
status:
  compute_from: html.elements.del
compat_features:
  - api.SVGAnimateColorElement
  - html.elements.del
```

`npm run dist -- path/to/file` does not print a warning.

Ideally, it would also show the deprecated keys, but it looks like that is a bit harder to surface.
