### ISSUE TITLE
How can we remember to update baseline status, dates, and browser versions of hard-coded features?

### ISSUE THREAD

**Issue by captainbrosset** [web-platform-dx/web-features#2364]
The following features have hard-coded baseline/browser statuses:

* autofocus
* avif
* datalist
* http2
* http3
* intersection-observer-v2
* jpegxl
* notifications
* scroll-to-text-fragment
* web-bluetooth
* webdriver-bidi
* webp

For example, scroll-to-text-fragment:

```
status:
  baseline: false
  support:
    chrome: "81"
    chrome_android: "81"
    edge: "83"
    safari: "16.1"
    safari_ios: "16.1"
```

Or, http2:

```status:
  baseline: high
  baseline_low_date: 2015-09-30
  support:
    chrome: "41"
    chrome_android: "41"
    edge: "12"
    firefox: "36"
    firefox_android: "36"
    safari: "9"
    safari_ios: "9"
```

Soon, we will also have notifications-app.yml ([PR](https://github.com/web-platform-dx/web-features/pull/1678/files)): 

```
status:
  baseline: low
  support:
    chrome: 20
    chrome_android: 42
    edge: 14
    firefox: 22
    firefox_android: 22
    safari: 7
    safari_ios: 16.4
```

How can we remember to update the status when necessary?
The last example I pasted will soon need to move from low to high, and a baseline_high_date will be needed.
