### ISSUE TITLE
Question: will there be a baseline_high_date field?

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-dx/web-features#522]
I was looking at recent updates to the [schema](https://github.com/web-platform-dx/web-features/blob/main/schemas/defs.schema.json) file. Upon examination, I had a quick question: will there be a baseline_high_date? 

For example, indeterminate is already marked as [high](https://github.com/web-platform-dx/web-features/blob/dfcd560dd00299d338ae3cdbf013b84d892056f2/feature-group-definitions/indeterminate.yml#L5C1-L8).

```yaml
status:
  baseline: high
  baseline_low_date: 2020-01-15
  support:
....
```

But as a consumer, I would be curious when it transitioned to `high`.  

cc: @foolip @atopal
