### ISSUE TITLE
Tracking single missing implementations to give developers a way to weigh in

### ISSUE THREAD

**Issue by captainbrosset** [web-platform-dx/web-features#591]
## Context

There's a risk with Baseline, that's also an opportunity at the same time. The risk is, with the way it appears on sites out there, that developers come to interpret Baseline as a signal not to look at things that aren't Baseline. However, those things are important too. They need community involvement, people looking into them, experimenting with them. People need to be able to get interested by those things and ask for them to be supported.

This is also an opportunity. The web-features repo, as a hub for simplified compat data, could make it obvious why certain features are not Baseline yet and, even more importantly, could tell consumers of the data what to do about it.

## Example

Take [the CSS Typed Object Model API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Typed_OM_API) (which I'm far from being an expert on, so take this with a grain of salt). Firefox is the only browser not to support it yet, apparently. Mozilla is [supportive of it](https://mozilla.github.io/standards-positions/#css-typed-om) though. This means the API is just not at the top of their priority list. In fact, [the tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1278697) for it, which has been opened 8 years ago now, is marked a P3, and only has 6 real comments on it.

How would someone signal their need for the feature? They'd have to know where to find the tracking bug, have a bugzilla account, and drop a comment or a vote.

With Baseline, there's a high chance that someone who stumbled on the documentation for the API, in search of something to accomplish their task, might just decide to ignore the API altogether, and use something else, without letting Mozilla know that they really would benefit from it, and why.

## Proposal

Add a list of URLs to web features that point to places where people can signal their need for the feature.

For the CSS Typed Object Model API, this could be:

```yaml
name: CSS Typed Object Model
spec: https://www.w3.org/TR/css-typed-om-1/
status:
  baseline: false
  support:
    chrome: "68"
    chrome_android: "66"
    edge: "79"
    opera: "53"
    opera_android: "47"
    safari: "16.4"
    safari_ios: "16.4"
  missing:
    firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1278697
```

The data for it will need to be manually maintained, but most of the data is already manually maintained anyway.

**Comment by captainbrosset** [comment]
Another example:

```yaml
name: Web Midi API
spec: https://webaudio.github.io/web-midi-api/
status:
  baseline: false
  support:
    ...
  missing:
    safari: https://bugs.webkit.org/show_bug.cgi?id=107250
```
