### ISSUE TITLE
Release web-features as GitHub release with JSON artefact

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#685]
We can probably copy the approach that BCD uses, with an attached `data.json`.
https://github.com/mdn/browser-compat-data/releases/tag/v5.5.15

Requested by @jcscottiii.

**Comment by foolip** [comment]
I have manually made a release in the shape I think we should automate:
https://github.com/web-platform-dx/web-features/releases/tag/web-features%2F0.6.0

**Comment by ddbeck** [comment]
I think we now need two artifacts.

The first is as described, including `data.json` without the npm package wrapper on GitHub releases.

The second would be a more comprehensive file containing the single-key status results of `getStatus()` for each feature. This has come by MDN's request, since they don't want a JS dependency for this data.

For the latter, I think we'll need some extension or variation on the schema for the purposes of this one file. Something like:

```yaml
status:
  baseline: false
  support:
    chrome: "95"
    edge: "95"
  by_compat_features_key:
    api.example.method:
      status:
        baseline: false
        support:
          chrome: "95"
          edge: "95"
    # etc.
```
