### ISSUE TITLE
Support overriding the a single browser's support in dist build

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#799]
In https://github.com/web-platform-dx/web-features/pull/797 I wanted to override the Chrome Android data, but found that this minimal override wouldn't work:

```yaml
status:
  baseline: false
  support:
    chrome_android: "121"
```

The generated YAML then had only Chrome Android, not the Chrome+Edge data that could be correctly generated.

There's a catch if we try to support this however. How would we erase a key that shouldn't be there? I would suggest setting support to false to achieve this.

**Comment by ddbeck** [comment]
Now that I've thought this through a bit (see below), I have one big question:

How does overriding a _single_ browser affect the calculation of `baseline` and `baseline_low_date`, if at all? For instance, does setting a version imply setting the version for the purposes of determining the `baseline_low_date`? Or is it like giving a directive to edit the YAML in a certain way?

----

Thinking through alternatives here, just to get my head around how it'd work.

## Explicitly generate

A special "accept calculated" value

```yaml
status:
  baseline: accept
  support:
    chrome: accept
    chrome_android: "121"
    edge: accept
    # etc. …
```

## Semi-explicit pass-through

Undefined values get generated

```yaml
status:
  baseline:
  support:
    chrome:
    chrome_android: "121"
    edge:
    # etc. …
```

## Some sort of special override notation

```yaml
editorial:
  - status.baseline: false
  - status.support.chrome_android: 121
