### ISSUE TITLE
Support excluding individual BCD keys

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#841]
Right now we have to provide a full `compat_features` list in order to override any issues with the tagging in BCD. Instead, let's have something like this:

```yaml
name: WebUSB
spec: https://wicg.github.io/webusb/
caniuse: webusb
usage_stats: https://chromestatus.com/metrics/feature/timeline/popularity/1519
ignore_compat_features:
  - api.USBDevice.forget
  - api.WorkerNavigator.usb
  - http.headers.Permissions-Policy.usb
```

**Comment by foolip** [comment]
That example is what https://github.com/web-platform-dx/web-features/pull/842 would turn into. It's quite the difference!

**Comment by foolip** [comment]
I think it might be smart to put things like this in an `overrides` field that could be passed to `computeBaseline` pretty much as-is. Something like this:

```yaml
name: WebUSB
spec: https://wicg.github.io/webusb/
caniuse: webusb
usage_stats: https://chromestatus.com/metrics/feature/timeline/popularity/1519
overrides:
  edge: "79" # hypothetically, if it was wrong
  compat_features:
    include:
      - api.Hypothetical.something
    exclude:
      - api.USBDevice.forget
      - api.WorkerNavigator.usb
      - http.headers.Permissions-Policy.usb
```
