### ISSUE TITLE
Treat groups as "living features"

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/web-features#866]
@foolip and I were talking today about how to deal with "tidying" events in feature development. Sometimes an API will get a new method or property (e.g., a DOM attribute reflection) that gives symmetry to similar surfaces, but might not be a recognizably standalone "feature" itself.

For instance, we saw that some CSS properties acquired logical properties that didn't previously have them: `inline-start` and `-end` values. It'd be sort of silly to describe the expansion of those values as a feature _together_ (given that they apply to unrelated properties) or individually (if you care about them individually, you'll look them individually).

And yet, logical values _in general_ is an interesting thing to know about. You could, for instance, explore _all_ the properties that support such values or see the overall progress of implementation across all the relevant properties, if that's something you care about.

So it might be interesting to test out treating groups as clearinghouses for related things and even generate support information for them. For many features it's likely the top-line Baseline status will be deeply uninteresting—it suggests we should have a "partial" status to make that explicit—but the support data itself might be helpful for understanding how the overall group relates to the individual values, properties, methods, etc.

cc: @Elchi3

**Comment by ddbeck** [comment]
Oh one more thought here:

The groups might be a helpful place to mark the "entry point" into the feature. For instance, if you looked up "root font size units"—as a group—over the years, you might see that it was "partially" implemented at some point. But it'd be quite clever if that group could mark out `rem` as the initial entry point (and that it has very long standing support).

**Comment by atopal** [comment]
I like the idea. It seems to me that this might indeed be somewhat
irrelevant for web developers, but it could be very relevant to
implementers to have an overview of an area and its implementation status.

**Comment by foolip** [comment]
A few other options:

- Having features as living features, with `living: true` or something, and the expectation that those aren't imported to caniuse since they're not especially useful for web developers.
- A more general draft features option which aren't published at all, but are a place for us to stash things before we know what to do with them.

**Comment by foolip** [comment]
I think that something like this, with an "initial" and a "living" aspect to a feature, is what will resolve discussions like that in https://github.com/web-platform-dx/web-features/pull/873. cc @Elchi3

**Comment by ddbeck** [comment]
Thanks to the discussion on Thursday and looking closely at #873, I think I'm coming up with better ways to think about this. First, I think I can distinguish three problems, some of which living features might help (or not):

- **The junk drawer problem**: sometimes random new things appear on existing APIs. They're not necessarily features in isolation (e.g., a reflection property added later is not as meaningful as the behavior given by the property itself). But it'd be nice to put them into features not so much for the status of everything together, but to get the status of the individual leaves (e.g., to find out which individual properties and methods of an API are Baseline, even if they're not part of a distinct feature).

- **The false breakage problem**: suppose a long-established CSS property gets a new logical value, for completeness and symmetry with other properties. Adding a newer subfeature advances the Baseline date, which creates the false appearance of instability. I think this is pretty serious because **the same date advance would take place if the feature broke support continuity** (e.g., some browser unshipped then re-shipped the feature).

- **The reverse-aging problem**: a feature emerges, then is followed shortly by some enhancements that are a recognizably distinct feature (e.g., `Map` and iterable `Map`, grid and subgrid). Five years go by. We and developers now recognize those things as one unit (`Map`; grid layout). If we merge them, it now appears as if the feature is younger than it actually is. It implies novelty and goes contrary to developer expectations ("wait, I've been using grid way longer than that…").

**Comment by foolip** [comment]
Here are the concepts I think we need to be tracking:

- Frozen features as "[finalized thing that happened at particular date](https://github.com/web-platform-dx/web-features/pull/873#issuecomment-2069326274)", to quote @Elchi3. For example, the global `fetch()` method shipped in specific browser versions, and this will never change, regardless of what additions happens in or around `fetch()`.
- Living features as they are used and understood by web developers today. For example, abortable fetch is or will be part of the living `fetch()` feature, not forever distinct. Most information we have about features can only be about the living feature, including developer signals and usage metrics. Tests can in theory be frozen in scope, but in practice they evolve along the living feature too.
- Groups of features to express broad technology areas like JavaScript, HTML, and slightly narrower ones like HTML media elements.

Since we've been defining features in terms of BCD keys, and because we've tried to match caniuse versions, we now have frozen features as the de-facto practice.

How do we represent living features? This issue and https://github.com/web-platform-dx/web-features/pull/873#issuecomment-2069326274 suggests using groups for this. I think that will work for a lot of JavaScript which has evolved in relatively clean steps that we can put names on, often because they started out as named proposals in TC39.

However, I think this won't work as well for much of the web platform that grows in tens or hundreds of small steps, in different orders in different browsers, and usually without a way to refer to a set of additions. I think that in practice it will result in most features having a group by the same name.

I've been wondering what it would look like to have features represent both their initial support and the living evolving feature, in a way that would work with a "tag everything" approach in BCD.

My tentative idea is that web-features puts either or both of the initial feature or the evolved feature into different lists. Taking [container queries](https://github.com/web-platform-dx/web-features/blob/29d7b5b278cb86e0c021a94123cbd530d3aae131/feature-group-definitions/container-queries.yml) as the example, we might turn it into something like this:

```yaml
name: Container queries
description: Container size queries with the `@container` at-rule apply styles to an element based on the dimensions of its container.
spec: https://drafts.csswg.org/css-contain-3/#container-queries
caniuse: css-container-queries
usage_stats: https://chromestatus.com/metrics/feature/timeline/popularity/4165
compat_features:
  initial_support:
    - api.CSSContainerRule
    - css.at-rules.container
    - css.properties.contain
    - css.properties.contain.inline-size
    - css.properties.contain.style
    - css.properties.container
    - css.properties.container-name
    - css.properties.container-name.none
    - css.properties.container-type
    - css.properties.container-type.inline-size
    - css.properties.container-type.normal
    - css.properties.container-type.size
    - css.types.length.container_query_length_units
  later_support:
    - api.CSSContainerRule.containerName
    - api.CSSContainerRule.containerQuery
```

We could enforce that everything in `later_support` would actually change some browser version. Possibly `initial_support` could be implied, so that nothing is needed in case the feature doesn't evolve at all.

A `later_support` list might grow for a while before we realize that a new feature is warranted. At that point we might consider if we should define subfeatures (a `parent` field for features), list features under `later_support`, or something like that.

I don't think this structure would be ideal for Array where we have lots of identifiable subfeatures, but I think it would be suitable for a large majority of features that we've been dealing with in web-features so far.

**Comment by ddbeck** [comment]
My first reaction is that I like this distinction between initial support and later support. It does a lot of nice things at once:

- It has a pretty obvious automation story (e.g., new keys appearing in a tag in BCD have somewhere sensible to go by default, once we've "frozen" feature).
- It offers an answer to the "junk drawer" problem: I can put somewhat related things together and have a pretty good idea of how weird or surprising it would be to pull it out of that bin to create a new feature later (if and when I get it wrong). If I'm pulling from `later_support`, then I know that creating a new feature is adding more granularity our description of the platform as a whole. If it's in `initial_support`, then I know that I'm potentially breaking (or aligning) with stronger commitments about what that feature is.
- It offers an answer to the "false breakage" and "reverse aging" problems: I can put related things together without changing the story that we're telling about that feature's history.

I'd expect that, if we use the two tiers appropriately, then we ought to expect:

1. To mint new features mostly from brand new keys or later support keys (and rarely from initial support keys).
2. To rarely promote or demote keys _within_ an existing feature (at least, not long after its initial publication). Shuffling keys within a feature will probably signal we're on the wrong track.
3. To satisfy most compat key overrides uses (e.g., the current crop of non-data-quality exclusions).

The one bit of this that I'm _slightly_ uncomfortable with is that it muddies the water for consumers of BCD and web-features about the least common denominator of support status. So far, we're (usually) saying that for every compat key in a given feature that key has as good or better support than the headline support status information. If we do this, I think we should take steps to bless single-compat key results of compute-baseline, so that consumers like MDN can show an approved status for fine-grained features in the later support bucket (e.g., if you're on a page for a later-support key, then they get a banner specifically about that key, not the whole feature).

**Comment by foolip** [comment]
To use another example, here's what I'd like to see when reviewing `contain-intrinsic-size`:

```yaml
# 1st bit of the feature, retroactively considered partial
status:
  baseline: low
  baseline_low_date: 2023-09-18
  support:
    chrome: "83"
    chrome_android: "83"
    edge: "83"
    firefox: "107"
    firefox_android: "107"
    safari: "17"
    safari_ios: "17"
compat_features:
  - css.properties.contain-intrinsic-size

# 2nd bit, and the block used for the feature's overall status
status:
  baseline: low
  baseline_low_date: 2023-09-18
  support:
    chrome: "95"
    chrome_android: "95"
    edge: "95"
    firefox: "107"
    firefox_android: "107"
    safari: "17"
    safari_ios: "17"
compat_features:
  - css.properties.contain-intrinsic-block-size
  - css.properties.contain-intrinsic-height
  - css.properties.contain-intrinsic-inline-size
  - css.properties.contain-intrinsic-width

# 3rd bit, a new addition to the feature
status:
  baseline: low
  baseline_low_date: 2023-09-18
  support:
    chrome: "117"
    chrome_android: "117"
    edge: "117"
    firefox: "117"
    firefox_android: "117"
    safari: "17"
    safari_ios: "17"
compat_features:
  - css.properties.contain-intrinsic-size.auto_none
```
