### ISSUE TITLE
compute-baseline doesn't handle Edge 79 removal correctly 

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#876]
Generating `audio-video-tracks.dist.yml` currently produces this:

```yml
# Generated from: audio-video-tracks.yml
# Do not edit this file by hand. Edit the source file instead!

name: Audio and video tracks
description: The `audioTracks` and `videoTracks` APIs for media elements switch audio and video tracks during playback.
group: media-elements
spec: https://html.spec.whatwg.org/multipage/media.html#media-resources-with-multiple-media-tracks
caniuse:
  - audiotracks
  - videotracks
status:
  baseline: false
  support:
    edge: "12"
    safari: "8"
    safari_ios: "8"
compat_features:
  - api.AudioTrack
  - ...
```

Edge 12 is wrong, see here:
https://developer.mozilla.org/en-US/docs/Web/API/AudioTrack#browser_compatibility
